# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'N-BBang' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RIBs'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Mantis'
  pod 'RxDataSources'
  pod 'WSTagsField'

  # Pods for N-BBang

end